import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: {
        default: "Next.js Tutorial",
        template: "%s | whoami",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className='w-full py-8 bg-linear-90 to-blue-500 from-purple-500 flex items-center justify-center text-white font-semibold font-mono text-2xl'>Header</header>
                {children}
                <footer className='w-full py-8 bg-linear-90 to-purple-500 from-blue-500 flex items-center justify-center text-white font-semibold font-mono text-2xl'>Footer</footer>
            </body>
        </html>
    );
}
